### ISSUE TITLE
DEMO线上运行良好，本地运行报错

### ISSUE THREAD

**Issue by cwandev** [shengxinjing/benben#1]
大圣老师好！

我直接clone到本地，在 env 文件换上key以后，报这样的一个错误，您知道怎么解决吗？

<img width="711" alt="截屏2023-03-06 16 41 19" src="https://user-images.githubusercontent.com/22477554/223059632-b5000067-8cdf-4ae5-bb86-ea6e5dd84495.png">

![截屏2023-03-06 16 43 48](https://user-images.githubusercontent.com/22477554/223060226-a761bfc8-496c-46d5-828e-459e7bea2511.png)

**Comment by wangfengyuan** [comment]
> 大圣老师好！
> 
> 我直接clone到本地，在 env 文件换上key以后，报这样的一个错误，您知道怎么解决吗？
> 
> <img alt="截屏2023-03-06 16 41 19" width="711" src="https://user-images.githubusercontent.com/22477554/223059632-b5000067-8cdf-4ae5-bb86-ea6e5dd84495.png">
> 
> ![截屏2023-03-06 16 43 48](https://user-images.githubusercontent.com/22477554/223060226-a761bfc8-496c-46d5-828e-459e7bea2511.png)

fetch是node18才内置的，需要切换到node18

**Comment by cwandev** [comment]
@wangfengyuan 已经在使用node最新版本了，不过还是报同样的错误

**Comment by wangfengyuan** [comment]
> 

那就是这个api地址被墙了，需要开全局代理吧
